blank_issues_enabled: false
contact_links:
  - name: Information
    url: https://en.wikipedia.org/wiki/Phineas_and_Ferb
    about: the lore
  - name: Inators
    url: https://phineasandferb.fandom.com/wiki/List_of_Doofenshmirtz%27s_schemes_and_inventions
    about: inator list
