name: Inator
description: File an inator report.
title: "[Inator]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this inator report!
  - type: input
    id: inator
    attributes:
      label: inator Details
      description: How can we inator
      placeholder: ex. inator
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: WE NEED TO MAKE MORE INATORS
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 3 (Default)
        - 1000000.0 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: inators
    attributes:
      label: What inators are you seeing the problem on?
      multiple: true
      options:
        - breadinator
        - cookinator
        - drillinator
        - other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](http://meals.legacyminigames.net). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
